package com.example.utils

import kotlinx.serialization.Serializable

@Serializable
enum class ErrorCode {
    INCORRECT_CREDENTIALS,
    USER_NOT_FOUND,
    BLANK_CREDENTIALS,
    SHORT_PASSWORD,
    USER_ALREADY_EXISTS,
    SERVER_ERROR,
    CHECK_CREDENTIALS,
    INCORRECT_PHONE,
    INCORRECT_ADDRESS,
    INCORRECT_NAME,
    RECIPIENT_ALREADY_EXISTS,
    RECIPIENT_NOT_FOUND,
    ADDRESS_NOT_FOUND,
    UNAUTHORIZED,
    NOTHING_CHANGED
}