ktor:
  application:
    modules:
      - com.example.ApplicationKt.module
  deployment:
    port: 8080
  jwt:
    secret: $jwt-secret
    issuer: "http://localhost:8080"
    audience: "http://localhost:8080"
    realm: "Access protected routes"
    expiry: "86400000"
postgres:
  url: "jdbc:postgresql://localhost/default"
