ktor:
  application:
    modules:
      - com.example.ApplicationKt.module
  deployment:
    port: 52144
  jwt:
    secret: $JWT_SECRET
    issuer: "http://localhost:8080"
    audience: "http://localhost:8080"
    realm: "Access protected routes"
    expiry: "900000"
  postgres:
    url: $POSTGRES_URL
    user: $POSTGRES_USER
    password: $POSTGRES_PASSWORD
  refresh:
    expiry: "604800000"
    length: "32"
